/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Questao03.view;

import Questao03.Pesquisa;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel Melo
 */
public class Tela03 extends javax.swing.JFrame {

    /**
     * Creates new form Tela03
     */
    public Tela03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnnenhum = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        green = new javax.swing.JRadioButton();
        blue = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pink = new javax.swing.JRadioButton();
        nenhuma = new javax.swing.JRadioButton();
        red = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnenhum.add(green);
        green.setText("Verde");
        green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenActionPerformed(evt);
            }
        });
        jPanel1.add(green, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 55, -1, -1));

        btnnenhum.add(blue);
        blue.setText("Azul");
        jPanel1.add(blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, -1, -1));

        jButton1.setText("Votar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 194, 260, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Qual sua cor favorita?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 260, -1));

        btnnenhum.add(pink);
        pink.setText("Rosa");
        jPanel1.add(pink, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnnenhum.add(nenhuma);
        nenhuma.setText("Nenhuma das opções");
        nenhuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nenhumaActionPerformed(evt);
            }
        });
        jPanel1.add(nenhuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 131, -1, -1));

        btnnenhum.add(red);
        red.setText("Vermelho");
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redActionPerformed(evt);
            }
        });
        jPanel1.add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, -1, 20));

        jButton2.setText("Finalizar Pesquisa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greenActionPerformed

    private void redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redActionPerformed

    private void nenhumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nenhumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nenhumaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
      
        if (red.isSelected()) {
            
       Pesquisa.red=Pesquisa.red+1;
       Pesquisa.totalvotos=Pesquisa.totalvotos+1;
            System.out.println("Total de votos Vermelho"+Pesquisa.red);
             System.out.println("Total de votos"+Pesquisa.totalvotos);
              
            int con=JOptionPane.showConfirmDialog(null, "Deseja Continuar com a Pesquisa?");
            
            if(con!=0){
               System.out.println(con);
                 JOptionPane.showMessageDialog(null,"Total de Pessoas"
                + " que votaram\n"+Pesquisa.totalvotos+"\nTotal de Votos Vermelhos:"+Pesquisa.red+
                "\nTotal de Votos Verdes:"+Pesquisa.green+
       "\nTotal de Votos Rosa:"+Pesquisa.pink+
                "\nTotal de Votos Azul:"+Pesquisa.blue+
                "\nTotal de Votos Nenhuma da Opções:"+Pesquisa.nenhum);
        System.exit(0);
            }
        }
       
       
        if (pink.isSelected()) {
 Pesquisa.pink=Pesquisa.pink+1;
       Pesquisa.totalvotos=Pesquisa.totalvotos+1;
            System.out.println("Total de votos Rosa"+Pesquisa.pink);
             System.out.println("Total de votos"+Pesquisa.totalvotos);
                 int con=JOptionPane.showConfirmDialog(null, "Deseja Continuar com a Pesquisa?");
            
            if(con!=0){
               System.out.println(con);
                 JOptionPane.showMessageDialog(null,"Total de Pessoas"
                + " que votaram\n"+Pesquisa.totalvotos+"\nTotal de Votos Vermelhos:"+Pesquisa.red+
                "\nTotal de Votos Verdes:"+Pesquisa.green+
       "\nTotal de Votos Rosa:"+Pesquisa.pink+
                "\nTotal de Votos Azul:"+Pesquisa.blue+
                "\nTotal de Votos Nenhuma da Opções:"+Pesquisa.nenhum);
        System.exit(0);
            }
        }
        if (blue.isSelected()) {
 Pesquisa.blue=Pesquisa.blue+1;
       Pesquisa.totalvotos=Pesquisa.totalvotos+1;
            System.out.println("Total de votos Azul"+Pesquisa.blue);
             System.out.println("Total de votos"+Pesquisa.totalvotos);
                 int con=JOptionPane.showConfirmDialog(null, "Deseja Continuar com a Pesquisa?");
            
            if(con!=0){
               System.out.println(con);
                 JOptionPane.showMessageDialog(null,"Total de Pessoas"
                + " que votaram\n"+Pesquisa.totalvotos+"\nTotal de Votos Vermelhos:"+Pesquisa.red+
                "\nTotal de Votos Verdes:"+Pesquisa.green+
       "\nTotal de Votos Rosa:"+Pesquisa.pink+
                "\nTotal de Votos Azul:"+Pesquisa.blue+
                "\nTotal de Votos Nenhuma da Opções:"+Pesquisa.nenhum);
        System.exit(0);
            }
        }
        if (green.isSelected()) {
            
             Pesquisa.green=Pesquisa.green+1;
       Pesquisa.totalvotos=Pesquisa.totalvotos+1;
            System.out.println("Total de votos Verde"+Pesquisa.green);
             System.out.println("Total de votos"+Pesquisa.totalvotos);
                 int con=JOptionPane.showConfirmDialog(null, "Deseja Continuar com a Pesquisa?");
            
            if(con!=0){
               System.out.println(con);
                 JOptionPane.showMessageDialog(null,"Total de Pessoas"
                + " que votaram\n"+Pesquisa.totalvotos+"\nTotal de Votos Vermelhos:"+Pesquisa.red+
                "\nTotal de Votos Verdes:"+Pesquisa.green+
       "\nTotal de Votos Rosa:"+Pesquisa.pink+
                "\nTotal de Votos Azul:"+Pesquisa.blue+
                "\nTotal de Votos Nenhuma da Opções:"+Pesquisa.nenhum);
        System.exit(0);
            }

        }
        if (nenhuma.isSelected()) {
            
             Pesquisa.nenhum=Pesquisa.red+1;
       Pesquisa.totalvotos=Pesquisa.totalvotos+1;
            System.out.println("Total de votos Nenhuma"+Pesquisa.nenhum);
             System.out.println("Total de votos"+Pesquisa.totalvotos);
                 int con=JOptionPane.showConfirmDialog(null, "Deseja Continuar com a Pesquisa?");
            
            if(con!=0){
               System.out.println(con);
                 JOptionPane.showMessageDialog(null,"Total de Pessoas"
                + " que votaram\n"+Pesquisa.totalvotos+"\nTotal de Votos Vermelhos:"+Pesquisa.red+
                "\nTotal de Votos Verdes:"+Pesquisa.green+
       "\nTotal de Votos Rosa:"+Pesquisa.pink+
                "\nTotal de Votos Azul:"+Pesquisa.blue+
                "\nTotal de Votos Nenhuma da Opções:"+Pesquisa.nenhum);
        System.exit(0);
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Total de Pessoas"
                + " que votaram\n"+Pesquisa.totalvotos+"\nTotal de Votos Vermelhos:"+Pesquisa.red+
                "\nTotal de Votos Verdes:"+Pesquisa.green+
       "\nTotal de Votos Rosa:"+Pesquisa.pink+
                "\nTotal de Votos Azul:"+Pesquisa.blue+
                "\nTotal de Votos Nenhuma da Opções:"+Pesquisa.nenhum);
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton blue;
    private javax.swing.ButtonGroup btnnenhum;
    private javax.swing.JRadioButton green;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton nenhuma;
    private javax.swing.JRadioButton pink;
    private javax.swing.JRadioButton red;
    // End of variables declaration//GEN-END:variables
}
